### ISSUE TITLE
Warning passing char ** to const char **

### ISSUE THREAD

**Issue by markand** [christophercrouzet/rexo#11]
Hi,

There is a warning because `rx_main` takes a `const char **` (which is incompatible with `char **`) that can be seen with `-Wall -Wextra`.

[Const correctness](http://c-faq.com/ansi/constmismatch.html) of double pointers is somewhat often misunderstood, I admit.

```
test/base64.c:389:32: warning: passing argument 4 of 'rx_main' from incompatible pointer type [-Wincompatible-pointer-types]
  389 |  return rx_main(0, NULL, argc, argv) == RX_SUCCESS ? 0 : 1;
      |                                ^~~~
      |                                |
      |                                char **
In file included from test/base64.c:21:
extern/librexo/rexo.h:6689:22: note: expected 'const char **' but argument is of type 'char **'
 6689 |         const char **argv)
```

**Comment by christophercrouzet** [comment]
I don't think that `const char * const *` adds any meaningful value over `const char**`.

The latter is basically synonym to passing a pointer by value that points to a const char array. The data that the caller owns, that is the char array, is guaranteed to not be able to change (well, at least that's the contract that is defined by the API). And that's all the caller cares about.

However yes, like you mentioned, we are able to change the value of the pointer itself if our function's implementation requires it, and there is nothing wrong with that since this doesn't make any difference for the caller. Only the pointer value that is local to our function's scope changes, not the pointed data! It's a feature, not something to guard against! :smile:

Let's substitute `char *` with `T` as you've already done it:

```C
void foo(T x)
{
    // The argument x is passed by value and it's now tied to the scope of
    // this function—we can do that we want with x without fearing to mutate
    // the original data from the caller.
    x += 123;
}

void bar(const T *x)
{
    // This time x is passed as a const pointer. We cannot mutate the data
    // pointed to, which is what `const` guarantees, however the pointer value
    // is tied to the scope of this function so, here again, we should be able
    // to do what we want with that pointer, such as using it like an iterator
    // for example.
    while (*x != 0)
    {
        ++x;
    }
}
```


Just to make sure, I tried changing the signature of `rx_main` to take `const char * const *` but I still had the same warning:

```c
passing 'char **' to parameter of type 'const char *const *' discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
```

> The only thing I could not understand is that a C compiler throws a warning while a C++ compiler doesn't roll_eyes

The C and C++ specs simply disagree on many points, and that's one of them. Is there a good reason for this constraint in C? Maybe not, which would explain why it's only a warning, not an error! :smile:

**Comment by christophercrouzet** [comment]
Thanks again for your time and patience @markand!

I just pushed the commit 23c966f047dbef810078ae19ace4795dc1fd5649 with the changes to address the `const` issue, however we're still left with the compiler warning which... I think is fine to just ignore since I would personally favour const-correctness over an arguable warning?

**Comment by christophercrouzet** [comment]
Thanks to your for your help and your kind words! :blush: 

> I have few ideas of improvements that I'll try to add at some point :)

I'm definitely looking forward to them! However I would like as much as possible to save you from spending time working on merge requests only for them to not being merged due to some possible disagreements, so I'd highly encourage you to first open new issues so that we can discuss things beforehand if that makes sense? :blush:
