### ISSUE TITLE
vcpkg port

### ISSUE THREAD

**Issue by SamuelMarks** [christophercrouzet/rexo#7]
https://github.com/microsoft/vcpkg/pull/18895

Want a PR to your CI/CD [GitHub Actions] to automatically send Microsoft a PR when you update your master?

**Comment by christophercrouzet** [comment]
Hello @SamuelMarks!

Thank you for taking the initiative of adding Rexo to vcpkg, that's awesome! And thanks also for offering to work on this PR!

I'm not sure how I feel about opening a PR whenever master is updated—this could easily become a bit... spammy? I couldn't find anything on the subject—is this a common and documented practice among the vcpkg community?

Also, wouldn't it be better to have vcpk point to a tagged version instead of the latest commit on the master branch? Of course, that is assuming that I would create more regular releases, which I will if I know that there's a need for it.

**Comment by SamuelMarks** [comment]
Yeah, might be a little spammy not sure if others do the same (though I assume they do).

Alright just tag me when you want this added, e.g., once vcpkg has merged my first commit and you've moved to a tag-release model

**Comment by christophercrouzet** [comment]
Alrighty, I've created a new tag release v0.2.0! (I really should add a changelog as well, but I'll do that another time (hopefully)).

From now on, I'll create new tags when deemed necessary but Rexo covers my current needs for now so I don't expect doing too much work on it, meaning that new tag releases will probably be fairly rare/sparse.

For that reason, I think that I'd rather manually open PRs on vcpkg's repository rather than adding an automation process for it. Not only would it feel ‘more human’ to do so but also the less code there is to maintain here, the better! :smile: 

Would that work for you?

Note: I've renamed the branch ‘master’ to ‘main’ in order to comply with recent diversity and inclusion guidelines.
